# Site settings
title: "Government of BC - Innovator's Toolkit"

# Site description
description: "This toolkit offers a set of steps that can be followed when developing a digital service."

# Site paths - set these in production!
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Excerpt the first sentence and use that for the .excerpt
# Alternatively, we could pipe the excerpt to truncatewords:75
excerpt_separator: .

# Build settings
markdown: kramdown

# URL settings
permalink: pretty

# Collections
collections:
  guides:
    output: true
    permalink: /guides/:path/
  steps:
    output: true
    permalink: /steps/:path/
  in-practice-examples:
    output: true
    permalink: /steps/in-practice-examples/:name/

# Defaults
# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: "steps/*"
      type: "pages"
    values:
      layout: "step"
#   -
#     scope:
#       path: "projects"
#       type: "pages" # previously `page` in Jekyll 2.2.
#     values:
#       layout: "project" # overrides previous default layout
#       author: "Mr. Hyde"

# Exclude these from processing.
# Do not remove.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - src
  - workfiles
  - NOTES
  - CONTRIBUTING.md
  - LICENCE
  - README.md
  - webpack.config.js
